### ISSUE TITLE
Add rate limiting for tenants

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-proxy#121]
It would be nice to implement rate limiting mechanism in Capsule proxy to stop a client (tenant) from making too many requests during a window of time. Many techniques are available in HTTP proxies, even more sophisticated. For our purpose, a simple rate limit for tenants should be enough, just as a matter of keeping upstream kubernetes APIS server usage fair.

**Comment by prometherion** [comment]
Actually, Kubernetes offers a [flow control set of APIs](https://kubernetes.io/docs/concepts/cluster-administration/flow-control/) starting from v1.20.

I wouldn't reinvent the wheel, what we have to check if during the __impersonate__ these constraints are honored, or not.

**Comment by prometherion** [comment]
Ok, just tested and verified that impersonation applies the `FlowSchema` rules and related `PriorityLevelConfiguration`.

I think we could avoid the implementation and, rather, document how to use this Kubernetes feature: WDTY @bsctl ?

**Comment by bsctl** [comment]
> I think we could avoid the implementation and, rather, document how to use this Kubernetes feature: WDTY @bsctl ?

Totally agree. Thanks!
