### ISSUE TITLE
[Doc] For running and testing capsule proxy on kind cluster

### ISSUE THREAD

**Issue by viveksyngh** [clastix/capsule-proxy#126]
Is there doc showing, how to run capsule proxy on a kind cluster ?

**Comment by ptx96** [comment]
Hello @viveksyngh, and thank you for your question.

You can follow guidelines describe inside the repository [README](https://github.com/clastix/capsule-proxy#run-locally-for-test-and-debug) ;

anyway,  take a look to a real example inside [Makefile](https://github.com/clastix/capsule-proxy/blob/master/Makefile) at `e2e/%: docker-build` step.

Please, let me know if you have any other questions 👍
