### ISSUE TITLE
Helm chart with default 0.1.1 version applies command with non-supported flag

### ISSUE THREAD

**Issue by maxgio92** [clastix/capsule-proxy#170]
It seems that the Chart with default values (`appVersion=0.1.1` that fils by default the OCI `capsule-proxy` image tag) generates the command with argument:
```
--rolebindings-resync-period=10h
```

but this flag seems not supported by the `capsule-proxy` binary which comes from the resulting `quay.io/clastix/capsule-proxy:v0.1.1` OCI image.

You can test the issue with Docker CLI by running:

```
docker run --rm quay.io/clastix/capsule-proxy:v0.1.1 --rolebindings-resync-period=10h
```

Am I missing something?

Thank you!

**Comment by prometherion** [comment]
`capsule-proxy` v0.2.0 is out there! 🚀
