### ISSUE TITLE
Undocumented feature about rolebindings

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-proxy#173]
There is an undocumented feature about `--rolebindings-resync-period` command option, most probably, related to #151.

**Comment by bsctl** [comment]
@MaxFedotov Could you please ad a short description of the feature, mainly for the user perspective? Thanks.

**Comment by prometherion** [comment]
@bsctl it seems documented to me.

https://github.com/clastix/capsule-proxy/blame/master/charts/capsule-proxy/README.md#L77

Can we close this?

**Comment by bsctl** [comment]
> it seems documented to me.

The issue refers to use the feature from user point of view: 
`options.rolebindingsResyncPeriod` | Set the rolebindings reflector resync period | `10h`

Just documenting the option above does not provide enough info to understand the meaning of this option. It would be nice @MaxFedotov provides a description of his use case which led to implement such feature. I remember we discussed a lot on Slack but it seems nothing has been reported into docs.
