### ISSUE TITLE
Helm chart version 0.1.4 applies command with non-supported flag

### ISSUE THREAD

**Issue by GlassOfWhiskey** [clastix/capsule-proxy#176]
Helm Chart version `0.1.4` is mapped onto Capsule Proxy version `0.1.0`, but it includes the flag `--capsule-configuration-name` in the proxy container's command. However, such flag is supported only by Capsule proxy version `>= 0.1.1` and the result is a crash loop of the proxy pods.

It seems that the Helm chart `0.1.4` has been erroneously updated to a new configuration. The fix would be to restore it to the original verison, the one with the `capsuleUserGroup` option.

**Comment by prometherion** [comment]
Thanks for reporting this, @GlassOfWhiskey.

I'm not a big fan of overwriting released versions and the fix should be using a previous version of the Chart, or upgrading `capsule-proxy`: what about closing this issue and using it as advice for any end-user who would encounter this issue?

**Comment by oliverbaehler** [comment]
Hi @GlassOfWhiskey if you need further assistance open a new issue. I will close this issue since the matter is outdated.
