### ISSUE TITLE
Refactoring tests

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule-proxy#193]
Tests are actually out of control.

Although `bats` is easy peasy, we're facing several issues with it, mostly regarding the copy/paste required across several test cases.

Furthermore, debugging the suite is tricky and error-prone, due to the limitations of bash.

We should investigate how to improve it, covering all the functionalities in each scenario (`kubectl`, http`, `TLS`, `User`, `Group`, `ServiceAccount`, etc.) and covering also #189 to avoid regressions.

**Comment by oliverbaehler** [comment]
I will close this issue in favor of #257
