### ISSUE TITLE
cert-gen for HTTPS fails during e2e tests stack setup

### ISSUE THREAD

**Issue by maxgio92** [clastix/capsule-proxy#221]
`cert-gen` Job fails because the Secret does not contain the `ca` Secret key.

**Comment by prometherion** [comment]
Faced the same issue, looking for help to address this.

**Comment by rakshpatel** [comment]
I'm new to open-source contribution and capsule-proxy. But based on the label, I can try this one if we have more information.

**Comment by rakshpatel** [comment]
@prometherion If this is still open. I can check if you can add more details

**Comment by prometherion** [comment]
Sorry @rakshpatel, I dunno why but I'm not anymore able to replicate the issue.

If it happens, I'll reopen it and assign it to you, thanks for your proactivity! <3
