### ISSUE TITLE
Support for RuntimeClasses

### ISSUE THREAD

**Issue by oliverbaehler** [clastix/capsule-proxy#260]
# Describe the feature

With the new tenant `v1beta2` tenants we can assign `RuntimeClasses` to Tenants. `capsule-proxy` should intercept `RuntimeClasses` and grant privileges according to tenant/proxysettings.

The RuntimeClass feature is documented here (should work like all the other cluster scoped class objects):

# What would the new user story look like?

As Enduser I would like to be able to list the RuntimeClasses which are assignable in my tenant.

**Comment by prometherion** [comment]
Closes via #702.
