### ISSUE TITLE
Error when using with Rancher

### ISSUE THREAD

**Issue by maxgio92** [clastix/capsule-proxy#264]
# Bug description

When using Capsule Proxy with Rancher Cluster Agent I get an error from the Cluster Agent tempting to apply the `cattle-system` Namespace.

# How to reproduce

Set the Rancher imported downstream cluster agent Kubernetes endpoint to the ones of Capsule Proxy (`KUBERNETES_SERVICE_HOST` and `KUBERNETES_SERVICE_PORT` env vars).

# Expected behavior

Capsule Proxy to let Cluster Agent runnig without errors when impersdonating the Rancher Dashboard user.

# Logs

```
Error while applying agent YAML, it will be retried automatically: exit status 1, clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged serviceaccount/cattle unchanged clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged secret/cattle-credentials-f600aba unchanged clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged deployment.apps/cattle-cluster-agent configured service/cattle-cluster-agent unchanged Error from server (AlreadyExists): error when creating "./management-statefile_path_redacted": namespaces "cattle-system" already exists
```

# Additional context

Cluster Agent group is part of the Capsule Proxy ignored groups.

**Comment by prometherion** [comment]
The attached PR is solving the issue by removing any extra header that the Rancher proxy is adding (`Impersonate-Extra-*`).

Tested on Rancher 2.7.1, please, @maxgio92 if you have the chance give it a try too.
