### ISSUE TITLE
Capsule Proxy claims resource it's created, but it's not available right away

### ISSUE THREAD

**Issue by JacekLakis-TomTom** [clastix/capsule-proxy#266]
# Bug description
When I create namespace via Capsule Proxy, it claims it's created, but when trying to read it, it's still unavailable for fraction of the second. Came across this issue when trying to use Terraform K8S provider to create namespace on behalf of a tenant. 

# How to reproduce
```
root@a301e2bba94d:/# k create ns alice-duck && k get ns alice-duck
namespace/alice-duck created
Error from server (NotFound): namespace "alice-duck" not found
```
or:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $BEARER" $APISERVER_HOST/api/v1/namespaces --data '{"metadata":{"name": "alice-duck"}}' &&
curl -X GET -H "Authorization: Bearer $BEARER" $APISERVER_HOST/api/v1/namespaces/alice-duck
```

# Expected behavior

I am able to read namespace after `POST` responds with success.

# Logs

Capsule proxy logs from the reproduced issue:
```
{"level":"Level(-8)","ts":"2023-03-03T11:22:11.997Z","logger":"proxy","msg":"Tenant","owner":"User","name":"bde577a6-7c17-4901-8097-3af6fa22383d","tenantList items":[{"kind":"Tenant","apiVersion":"capsule.clastix.io/v1beta1","metadata":{"name":"alice","uid":"3ee7e495-dfea-4e91-bfcf-645a68dcda4d","resourceVersion":"494505","generation":1,"creationTimestamp":"2023-03-02T08:20:40Z","annotations":{"capsule.clastix.io/deny-wildcard":"true","clusterrolenames.capsule.clastix.io/0":"admin,capsule-namespace-deleter","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"capsule.clastix.io/v1beta1\",\"kind\":\"Tenant\",\"metadata\":{\"annotations\":{},\"name\":\"alice\"},\"spec\":{\"namespaceOptions\":{\"quota\":2},\"owners\":[{\"kind\":\"User\",\"name\":\"bde577a6-7c17-4901-8097-3af6fa22383d\"}]}}\n"},"managedFields":[{"manager":"HashiCorp","operation":"Update","apiVersion":"capsule.clastix.io/v1beta1","time":"2023-03-02T08:20:40Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:namespaceOptions":{".":{},"f:quota":{}},"f:owners":{}}}},{"manager":"manager","operation":"Update","apiVersion":"capsule.clastix.io/v1beta2","time":"2023-03-02T08:20:42Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:namespaces":{},"f:size":{}}},"subresource":"status"}]},"spec":{"owners":[{"kind":"User","name":"bde577a6-7c17-4901-8097-3af6fa22383d"}],"namespaceOptions":{"quota":2},"ingressOptions":{"hostnameCollisionScope":"Disabled"},"networkPolicies":{},"limitRanges":{},"resourceQuotas":{"scope":"Tenant"}},"status":{"state":"Active","size":1,"namespaces":["alice-default"]}}],"number of tenants":1}
{"level":"Level(-4)","ts":"2023-03-03T11:22:12.000Z","logger":"proxy","msg":"Proxy tenant list","owner":"User","name":"bde577a6-7c17-4901-8097-3af6fa22383d","tenants":["alice"]}
{"level":"Level(-8)","ts":"2023-03-03T11:22:12.000Z","logger":"proxy","msg":"Tenant","owner":"Group","name":"095f78f8-2732-46ef-93ad-878992dec834","tenantList items":[],"number of tenants":0}
{"level":"Level(-4)","ts":"2023-03-03T11:22:12.000Z","logger":"proxy","msg":"Proxy tenant list","owner":"Group","name":"095f78f8-2732-46ef-93ad-878992dec834","tenants":[]}
{"level":"Level(-8)","ts":"2023-03-03T11:22:12.000Z","logger":"proxy","msg":"Tenant","owner":"Group","name":"system:authenticated","tenantList items":[],"number of tenants":0}
{"level":"Level(-4)","ts":"2023-03-03T11:22:12.000Z","logger":"proxy","msg":"Proxy tenant list","owner":"Group","name":"system:authenticated","tenants":[]}
{"level":"Level(-4)","ts":"2023-03-03T11:22:12.002Z","logger":"proxy","msg":"impersonating for the current request","username":"bde577a6-7c17-4901-8097-3af6fa22383d","groups":["095f78f8-2732-46ef-93ad-878992dec834","system:authenticated"]}
{"level":"Level(-5)","ts":"2023-03-03T11:22:12.002Z","logger":"proxy","msg":"debugging request","uri":"/api/v1/namespaces?fieldManager=kubectl-create&fieldValidation=Strict","method":"POST"}
{"level":"Level(-8)","ts":"2023-03-03T11:22:12.646Z","logger":"proxy","msg":"Tenant","owner":"User","name":"bde577a6-7c17-4901-8097-3af6fa22383d","tenantList items":[{"kind":"Tenant","apiVersion":"capsule.clastix.io/v1beta1","metadata":{"name":"alice","uid":"3ee7e495-dfea-4e91-bfcf-645a68dcda4d","resourceVersion":"495165","generation":1,"creationTimestamp":"2023-03-02T08:20:40Z","annotations":{"capsule.clastix.io/deny-wildcard":"true","clusterrolenames.capsule.clastix.io/0":"admin,capsule-namespace-deleter","kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"capsule.clastix.io/v1beta1\",\"kind\":\"Tenant\",\"metadata\":{\"annotations\":{},\"name\":\"alice\"},\"spec\":{\"namespaceOptions\":{\"quota\":2},\"owners\":[{\"kind\":\"User\",\"name\":\"bde577a6-7c17-4901-8097-3af6fa22383d\"}]}}\n"},"managedFields":[{"manager":"HashiCorp","operation":"Update","apiVersion":"capsule.clastix.io/v1beta1","time":"2023-03-02T08:20:40Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:namespaceOptions":{".":{},"f:quota":{}},"f:owners":{}}}},{"manager":"manager","operation":"Update","apiVersion":"capsule.clastix.io/v1beta2","time":"2023-03-02T08:20:42Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:namespaces":{},"f:size":{}}},"subresource":"status"}]},"spec":{"owners":[{"kind":"User","name":"bde577a6-7c17-4901-8097-3af6fa22383d"}],"namespaceOptions":{"quota":2},"ingressOptions":{"hostnameCollisionScope":"Disabled"},"networkPolicies":{},"limitRanges":{},"resourceQuotas":{"scope":"Tenant"}},"status":{"state":"Active","size":2,"namespaces":["alice-default","alice-duck"]}}],"number of tenants":1}
{"level":"Level(-4)","ts":"2023-03-03T11:22:12.647Z","logger":"proxy","msg":"Proxy tenant list","owner":"User","name":"bde577a6-7c17-4901-8097-3af6fa22383d","tenants":["alice"]}
{"level":"Level(-8)","ts":"2023-03-03T11:22:12.647Z","logger":"proxy","msg":"Tenant","owner":"Group","name":"095f78f8-2732-46ef-93ad-878992dec834","tenantList items":[],"number of tenants":0}
{"level":"Level(-4)","ts":"2023-03-03T11:22:12.647Z","logger":"proxy","msg":"Proxy tenant list","owner":"Group","name":"095f78f8-2732-46ef-93ad-878992dec834","tenants":[]}
{"level":"Level(-8)","ts":"2023-03-03T11:22:12.647Z","logger":"proxy","msg":"Tenant","owner":"Group","name":"system:authenticated","tenantList items":[],"number of tenants":0}
{"level":"Level(-4)","ts":"2023-03-03T11:22:12.647Z","logger":"proxy","msg":"Proxy tenant list","owner":"Group","name":"system:authenticated","tenants":[]}
2023/03/03 11:22:12 http: superfluous response.WriteHeader call from github.com/gorilla/handlers.recoveryHandler.ServeHTTP.func1 (recovery.go:73)
2023/03/03 11:22:12 namespace "alice-duck" not found
```
# Additional context

- Capsule-Proxy version: v0.3.3
- Helm Chart version: capsule-proxy-0.3.6
- Kubernetes version: v1.24.9

**Comment by prometherion** [comment]
The reason behind this is that Capsule Proxy is using a local cache backed by an in-memory one offered by the `controller-runtime` package.

A solution for this could be disabling the cache, with the downside of having the `capsule-proxy` hammering the Kubernetes API Server, and I would prefer having a cache with all the cons that put down the API Server.

How this is a blocker for you?

**Comment by JacekLakis-TomTom** [comment]
> How this is a blocker for you?

I can't use Capsule Proxy as an endpoint for Terraform provider. Provider throws `Root resource was present but now absent`. The reason is - according to [Terraform Resource Instance Change Lifecycle](https://github.com/hashicorp/terraform/blob/main/docs/resource-instance-change-lifecycle.md) and [this post](https://www.reddit.com/r/Terraform/comments/m5nv14/root_resource_was_present_but_now_absent/) - that it reads resource right after creation to check if what was applied really exists.

> A solution for this could be disabling the cache
Can I disable cache by CLI option / helm variable?

**Comment by prometherion** [comment]
> Can I disable cache by CLI option / helm variable?

Not right now, although we can work on that.

It's the first time I see the `capsule-proxy` being used instead of the API server since it could be used to simulate tenant owners using the impersonation (`--as` and `--as-group`).

I'm working on porting `v1beta2` Capsule changes for v0.4.0, we can add this too.

**Comment by JacekLakis-TomTom** [comment]
> It's the first time I see the capsule-proxy being used instead of the API server

I think I am missing something here. I want tenants to receive a single API Server endpoint to be used both for `kubectl` and terraform provider configuration. And I want to E2E test the terraform part. Is this an incorrect approach?

**Comment by prometherion** [comment]
I was able to test it with my dev env:

```
$: kubectl create ns oil-qa && kubectl get ns oil-qa
namespace/oil-qa created
NAME     STATUS   AGE
oil-qa   Active   0s
```

Going to land in v0.4.0

**Comment by JacekLakis-TomTom** [comment]
@prometherion Still not solved on my end for capsule-proxy 0.4.0, can this issue be re-opened? Trying with `kubectl create && get` also sometimes worked for me, but I can still reproduce issue with `curl` or in Terraform.  Curl:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $BEARER" $APISERVER_HOST/api/v1/namespaces --data '{"metadata":{"name": "alice-duck"}}' && curl -X GET -H "Authorization: Bearer $BEARER" $APISERVER_HOST/api/v1/namespaces/alice-duck

{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "alice-duck",
    "uid": "232ecc27-c098-4722-8fb5-74475f8a61a8",
    "resourceVersion": "1813291",
    "creationTimestamp": "2023-03-06T11:43:26Z",
    "labels": {
      "kubernetes.io/metadata.name": "alice-duck"
    },
    "ownerReferences": [
      {
        "apiVersion": "capsule.clastix.io/v1beta2",
        "kind": "Tenant",
        "name": "alice",
        "uid": "3ee7e495-dfea-4e91-bfcf-645a68dcda4d",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ],
    "managedFields": [
      {
        "manager": "curl",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2023-03-06T11:43:26Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:labels": {
              ".": {},
              "f:kubernetes.io/metadata.name": {}
            }
          }
        }
      }
    ]
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
}{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespace \"alice-duck\" not found","reason":"NotFound","details":{"name":"alice-duck","group":"v1","kind":"namespaces"},"code":404}
```
Terraform:
```
kubernetes_namespace_v1.test: Creating...
╷                                                                      
│ Error: Provider produced inconsistent result after apply
│                                                                      
│ When applying changes to kubernetes_namespace_v1.test, provider
│ "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an
│ unexpected new value: Root resource was present, but now absent.
│                                                                      
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.                                                   
╵                                                                      
ERRO[0005] Terraform invocation failed in /.../tenant-access 
ERRO[0005] 1 error occurred:                                           
        * exit status 1                                                
```

Also I saw your commits refer just to namespaces, but we would want to be able to create any kubernetes resource via Terraform provider. Disabling cache that you've mentioned before would solve the problem I guess.

**Comment by prometherion** [comment]
> Trying with `kubectl create && get` also sometimes worked for me, but I can still reproduce issue with `curl` or in Terraform

For Namespaces, we're not using anymore the local cache and it seems something related to your setup and out of Capsule Proxy control.

> Also I saw your commits refer just to namespaces, but we would want to be able to create any kubernetes resource via Terraform provider. Disabling cache that you've mentioned before would solve the problem I guess

Let's add a CLI flag that will use the API reader rather than the cached client.

**Comment by JacekLakis-TomTom** [comment]
Thank you so much @prometherion 
> it seems something related to your setup and out of Capsule Proxy control.

Wondering what this could be, I have no HTTP caching enabled, every request sequentially hits capsule-proxy, I can see it in the logs.  Also, I've just checked that error comes exactly from here:
https://github.com/clastix/capsule-proxy/blob/master/internal/modules/namespace/get.go#L59-L65
Perhaps caching is enabled in some inner request here?

**Comment by prometherion** [comment]
The portion of code you mentioned is using the API reader, and that's out of the equation.

**Comment by JacekLakis-TomTom** [comment]
Interesting, it seems to hit this method. I've added following change on top of `91735aef77675f01e0933563a755ca0573562676` commit:
```
diff --git a/internal/modules/namespace/get.go b/internal/modules/namespace/get.go
index 21df09a..6bf89b5 100644
--- a/internal/modules/namespace/get.go
+++ b/internal/modules/namespace/get.go
@@ -60,7 +60,7 @@ func (l get) Handle(_ []*tenant.ProxyTenant, proxyRequest request.Request) (sele
                return nil, errors.NewNotFoundError(fmt.Sprintf("namespace %q not found", name), &metav1.StatusDetails{
                        Name:  name,
                        Group: "v1",
-                       Kind:  "namespaces",
+                       Kind:  "namespaces A",
                })
        }
```
And built the image. Then, when running curl, I can see my change:
```
curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer $BEARER" $APISERVER_HOST/api/v1/namespaces --data '{"metadata":{"name": "alice-duck"}}' && curl -X GET -H "Authorization: Bearer $BEARER" $APISERVER_HOST/api/v1/namespaces/alice-duck
{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "alice-duck",
    "uid": "1ba7e27c-f8f7-44d3-9f72-1e6f364ddea7",
    "resourceVersion": "1834994",
    "creationTimestamp": "2023-03-06T12:53:35Z",
    "labels": {
      "kubernetes.io/metadata.name": "alice-duck"
    },
    "ownerReferences": [
      {
        "apiVersion": "capsule.clastix.io/v1beta2",
        "kind": "Tenant",
        "name": "alice",
        "uid": "3ee7e495-dfea-4e91-bfcf-645a68dcda4d",
        "controller": true,
        "blockOwnerDeletion": true
      }
    ],
    "managedFields": [
      {
        "manager": "curl",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2023-03-06T12:53:35Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:labels": {
              ".": {},
              "f:kubernetes.io/metadata.name": {}
            }
          }
        }
      }
    ]
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Active"
  }
}
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespace \"alice-duck\" not found","reason":"NotFound","details":{"name":"alice-duck","group":"v1","kind":"namespaces A"}
```

**Comment by JacekLakis-TomTom** [comment]
Is it possible that namespace is indeed created, but labels & owner references didn't get injected that fast so it doesn't recognize the tenant's namespaces?

**Comment by prometherion** [comment]
Nice catch, @JacekLakis-TomTom, it's the RoleBinding reflector: @MaxFedotov worked on that. IIRC, it's required since he's using it to allow list capabilities and `ServiceAccount` resources that have `admin` RoleBinding in the Tenants although not Tenant Owner.

We have a few options here:

1. suppressing the role binding reflector in favour of the `ProxySetting` resource introduced with Capsule Proxy
2. disabling the role binding reflector when using direct API server access

Since @MaxFedotov is a maintainer and using extensively the proxy in production, I'd like to get his feedback first.

**Comment by prometherion** [comment]
> Is it possible that namespace is indeed created, but labels & owner references didn't get injected that fast so it doesn't recognize the tenant's namespaces?

Thanks for pointing this out to me. We should check the `ownerReference` since labels are enforced upon Capsule reconciliation.

```bash
for I in {001..100}; do
kubectl create ns test-$I && kubectl get ns test-$I
done;
```

I was able to create and get all the Namespaces using the `capsule-proxy`.

I'll open a PR to discuss the required changes with @MaxFedotov.

**Comment by MaxFedotov** [comment]
Hey @prometherion and @JacekLakis-TomTom!

I remember why I added this feature. The idea was the following:
- `Tenant admin` create a `role` and `rolebinding` in one of his namespaces for user `Bob`. This `role` has a limited set of permissions (it is not `cluster-admin`)
- `Bob` must be able to see all `namespaces`, where he has access when running `kubectl get ns`

This reflector caches all `rolebindings` and is used for getting a list of namespaces to be shown for each of the users.
And as reflectors are asynchronous by default, this can add a delay between `kubectl create ns` and `kubectl get ns`

Now capsule-proxy adds new `ProxySetting` CRD, which can be used to add permissions for both, tenant admins and normal users. But removing this reflector would require tenant admins to create a separate `ProxySetting` CRD for each of the users `rolebindings` in all namespaces.

**Comment by prometherion** [comment]
> Now capsule-proxy adds new `ProxySetting` CRD, which can be used to add permissions for both, tenant admins and normal users. But removing this reflector would require tenant admins to create a separate `ProxySetting` CRD for each of the users `rolebindings` in all namespaces.

We can think about that later since it would be a breaking change.
