### ISSUE TITLE
don't validate client cert if TLSCertificate is not active

### ISSUE THREAD

**Issue by logikone** [clastix/capsule-proxy#271]
If the `--auth-preferred-types` cli flag is provided and `TLSCertificate` is not listed then there is no need validate a certificate if one is sent.

We're having troubles with this currently since the ingress controller we're using to expose capsule-proxy sends a client cert that is not signed by the kubernetes ca.

**Comment by prometherion** [comment]
> We're having troubles with this currently since the ingress controller we're using to expose capsule-proxy sends a client cert that is not signed by the kubernetes ca.

Shouldn't you use SSL pass-through?

**Comment by logikone** [comment]
We're wanting to terminate ssl at the ingress controller as we need to be [FIPS](https://www.nist.gov/standardsgov/compliance-faqs-federal-information-processing-standards-fips) compliant with all exposed services and our ingress controller is.

I'm unsure of the level of effort to get capsule-proxy compiled with goboring, but it may be something we want to look into?

**Comment by prometherion** [comment]
> I'm unsure of the level of effort to get capsule-proxy compiled with goboring, but it may be something we want to look into?

Any contribution is highly appreciated. The unique concern is to avoid as much as possible CGO, not sure if this is possible or not.

Feel free to open a feature request, looking forward to reviewing any PR!
