### ISSUE TITLE
error: got secret, but it did not contain a 'ca' key

### ISSUE THREAD

**Issue by sagar-jadhav** [clastix/capsule-proxy#285]
# Bug description

`capsule-proxy-certgen` Pod is failing with below error:

```
W0404 09:55:18.296470       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"level":"fatal","msg":"got secret, but it did not contain a 'ca' key","source":"k8s/k8s.go:114","time":"2023-04-04T09:55:18Z"}
```

# How to reproduce

Run the following commands:

- make kind
- make capsule
- make capsule-proxy

capsule-proxy helm chart will be installed but `capsule-proxy-certgen` Pod is failing and going into `error` state

# Expected behavior

`capsule-proxy-certgen` Pod should run without error and go to completed state.

**Comment by prometherion** [comment]
How are you installing `capsule-proxy`?

**Comment by sagar-jadhav** [comment]
@prometherion I am installing capsule-proxy using `make capsule-proxy` command. make command underlines uses helm to install capsule-proxy.
