### ISSUE TITLE
Create a Helm chart for installing this project

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-proxy#39]
Create a Helm chart for installing this project.

**Comment by MaxFedotov** [comment]
@bsctl i've already created a helm chart, which we are using internally. Can edit it a bit and make it public if you are ok with it :)

**Comment by bsctl** [comment]
> Can edit it a bit and make it public if you are ok with it :)

 extremely happy of that :)

**Comment by MaxFedotov** [comment]
@bsctl then I'll wait for @prometherion to merge my PR and rename the project to `capsule-api-proxy`, and then will make a PR

**Comment by prometherion** [comment]
@MaxFedotov merged as you wished.

Naming is hard, what about `capsule-proxy`?

**Comment by MaxFedotov** [comment]
That's sounds good too :)

**Comment by prometherion** [comment]
The plan is to create a new repository, deprecating this one: I'll arrange this.

**Comment by bsctl** [comment]
@prometherion how to just rename this repo without deprecation? I'll arrange to fix all the docs referring to it.
