### ISSUE TITLE
Access the node details

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-proxy#40]
The #38 introduce support for nodes filtering. With this PR only nodes listing is permitted.

```
$ kubectl get nodes 
NAME                STATUS   ROLES    AGE   VERSION
k8s-caas-worker01   Ready    worker   96d   v1.19.1
k8s-caas-worker02   Ready    worker   96d   v1.19.1
k8s-caas-worker03   Ready    worker   96d   v1.19.1
k8s-caas-worker04   Ready    worker   96d   v1.19.1
k8s-caas-worker05   Ready    worker   96d   v1.19.1
k8s-caas-worker06   Ready    worker   96d   v1.19.1

$ kubectl get node k8s-caas-worker01
Error from server (Forbidden): nodes "k8s-caas-worker01" is forbidden: User "alice" cannot get resource "nodes" in API group "" at the cluster scope
```
This is correct according to the initial feature request #21. It makes sense to give also the details of each node item for inspecting its status and monitoring.  I'm opening this feature request according to this [comment](https://github.com/clastix/capsule-ns-filter/pull/38#issuecomment-749169204)

**Comment by prometherion** [comment]
For this feature, we have to change the underlying `http` implementation, since the standard-library package doesn't support path parameter (e.g.: `/api/v1/nodes/{name}`).

Going to open an issue with a detailed description.

**Comment by prometherion** [comment]
This task was assigned to me but I'm looking for contributors, willing to help with the onboarding of the project and doing pair-programming and code reviews! 👀
