### ISSUE TITLE
Node listing should rely on the Tenant's nodeSelector spec

### ISSUE THREAD

**Issue by GlassOfWhiskey** [clastix/capsule-proxy#52]
Starting from capsule-proxy v0.0.5, it is possible to enable node listing for tenant owners through the `capsule.clastix.io/enable-node-listing` Tenant annotation.

The actual implementation requires a node to be explicitly labelled as `capsule.clastix.io/tenant=<Tenant Name>` to be listed by the corresponding Tenant owners. This implementation choice comes with some flaws:
- It does not support a scenario in which the same node is associated with multiple tenants
- It requires the cluster admin to explicitly add the `capsule.clastix.io/tenant=<Tenant Name>` to each node in the cluster, but this step is not documented
- It is totally unaware of the Tenant's `nodeSelector` spec. If a node is labelled as `capsule.clastix.io/tenant=<Tenant Name>` , tenant owners are able to list that node even if it violates the `nodeSelector` policy, i.e. even if they are not able to schedule pods on that node. Viceversa, if a node satisfies the `nodeSelector` policy but is not labelled as `capsule.clastix.io/tenant=<Tenant Name>`, users can schedule pods on it but are not able to list it.

It would be better to avoid configuration fragmentation for the node visibility feature: the same rule (preferably the `nodeSelector` spec, which allows node sharing among multiple tenants) should control both the node visibility in the capsule-proxy and the possibility to schedule pods on it.

**Comment by prometherion** [comment]
Thanks for reporting this @GlassOfWhiskey, I couldn't agree more about this, although it's going to be breaking for the actual adopter.

I'd like to address this for the upcoming minor version, `0.1.0`.

**Comment by Difrex** [comment]
Hi, I will do this task :)

**Comment by prometherion** [comment]
Thanks @Difrex, get in there! 🎉
