### ISSUE TITLE
Migrate to a better HTTP router

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule-proxy#54]
Actually, the HTTP server is using the standard library `http` that provides a basic router that doesn't allow to perform path variables matching.

What we have to implement is something as this:

```
r := mux.NewRouter()
r.HandleFunc("/api/v1/nodes", NodeListHandler)
r.HandleFunc("/api/v1/nodes/{name}", NodeHandler)
```

Implementing this enhancement gives us the chance to address and close #40, but last and not least, it's going to give us more flexibility on addressing future issues, as well as dealing in a better way with middleware and request filtering.

Along with this, we can also implement in a better way the middleware chains we're using, as:

https://github.com/clastix/capsule-proxy/blob/c34b1aa822c3e0fb958d76bab5d3b4466e3ed533/internal/webserver/webserver.go#L234-L235

I like [gorillamux](https://github.com/gorilla/mux) as well as [gin-gonic](https://github.com/gin-gonic/gin): probably the first choice is more reliable since it's standard-library compatible.

**Comment by davideimola** [comment]
Hi @prometherion 
If you want I can handle it!

**Comment by prometherion** [comment]
@davideimola it's up to you: don't hesitate to ping me for help on this.

**Comment by davideimola** [comment]
Thanks!
