### ISSUE TITLE
SSL self-signed certificate is not created when enabled in Helm chart

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-proxy#60]
The Helm chart defines an option for creating SSL self-signed certificate `options.generateCertificates`. Currently it is not working.

**Comment by prometherion** [comment]
I guess this was something @MaxFedotov have worked on, isn't it?

Let's mark this big as good-first-issue, easily to achieve :)

**Comment by prometherion** [comment]
Oh, just noticed you self assigned @bsctl 🤦🏻 

Are you working on this or let's ask for the community help?

**Comment by bsctl** [comment]
> Oh, just noticed you self assigned @bsctl 🤦🏻
> 
> Are you working on this or let's ask for the community help?

@prometherion working on it.

**Comment by MaxFedotov** [comment]
@bsctl ping me if some help needed with this :)
