### ISSUE TITLE
Switch over HTTP middlewares

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule-proxy#65]
We got several middlewares in the current codebase and strictly related to #54 once closed:

- [`isNamespaceListing`](https://github.com/clastix/capsule-proxy/blob/c3d7fda8da2aa7e006c0593aa4469355643b4a57/internal/webserver/webserver.go#L214-L221) checking if the request is a Namespace listing request, this can be safely dropped
- [`isNodeListing`](https://github.com/clastix/capsule-proxy/blob/c3d7fda8da2aa7e006c0593aa4469355643b4a57/internal/webserver/webserver.go#L223-L230) same as above, besides the fact addressing the node listing
- [`checkJwt`](https://github.com/clastix/capsule-proxy/blob/c3d7fda8da2aa7e006c0593aa4469355643b4a57/internal/webserver/webserver.go#L94-L122) that is checking the authentication provided by the bearer token

This last one must be converted to a middleware for all the routes transformed by `capsule-proxy`.

Although not properly a middleware, also the [`reverseProxyFunc`](https://github.com/clastix/capsule-proxy/blob/c3d7fda8da2aa7e006c0593aa4469355643b4a57/internal/webserver/webserver.go#L280-L297) could be considered a middleware, although performed after the single resource manipulation (`namespaces`, `nodes`, etc.): this could be splitted up in two middleware, the first one adding the __impersonate__ headers, and the second one performing the reverse proxy call.

Since the planned new routes are coming, we must group resources and apply middlewares.

**Comment by ludusrusso** [comment]
Hi @prometherion! I'd like to handle this :D

**Comment by prometherion** [comment]
It's yours!
