### ISSUE TITLE
Run in out-of-cluster mode

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule-proxy#67]
This idea started while investigating the code implementing #66 along with @ludusrusso.

Actually, `capsule-proxy` is just designed to run in the __in cluster__ configuration: this means the controller-runtime client will be feed with the CA certificate, the Bearer Token, and other options provided by the ServiceAccount volume mounted in the Pod.

The Bearer Token is definitely an important piece in the whole picture since it's the grant to get all the RBAC capabilities, as the user impersonification:

https://github.com/clastix/capsule-proxy/blob/888cab3ff2e233f330ec787626fc39643ca39f11/internal/webserver/webserver.go#L289-L291

Although this works in the __in cluster__ configuration, it's not the same for the __out of cluster__ mode: the reason is that a `kubeconfig` file is provided that could use the authentication based on a certificate rather than the JWT one.

We should investigate if we can use the Reverse Proxy transport to support the certificate authentication (if provided) and fallback to the bearer token: essentially, what we have to do is to set up the Transport for the Reverse Proxy to use the certificate if provided.

https://github.com/clastix/capsule-proxy/blob/888cab3ff2e233f330ec787626fc39643ca39f11/internal/webserver/webserver.go#L35-L37

With this, we're guaranteeing the ability to run also in the out-of-cluster mode, in production, or debug mode at end-user wish!

**Comment by prometherion** [comment]
Going to assign to @ludusrusso since you're already on track due to our previous investigation

**Comment by ludusrusso** [comment]
I'm in!

**Comment by bsctl** [comment]
@prometherion @ludusrusso definitively like the idea!
