### ISSUE TITLE
Removal of --k8s-control-plane-url CLI flag

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule-proxy#71]
With #68 we're totally relying on the configuration provided by the Service Account options (when running in in-cluster mode) or the provided `kubeconfig` file (when running in out-of-the-cluster mode).

The code actually warns users running the development branch of the deprecation policy: for 0.1.0 this has to be removed since there's any more need for it.

# Tasks

- [ ] [Update Helm chart](#105)
- [x] [Update code](#107)

**Comment by ludusrusso** [comment]
I'd like to work on it

**Comment by prometherion** [comment]
@ludusrusso this is the last PR for 0.1.0, are you still available on this issue?

**Comment by ludusrusso** [comment]
Yep! What do you mean here?

Update build files (./build)
