### ISSUE TITLE
Documenting new endpoints in the README

### ISSUE THREAD

**Issue by prometherion** [clastix/capsule-proxy#88]
We have to document how `capsule-proxy` behaves with listing the new resources:

- Node
- StorageClass
- IngressClass

I'm working on the IngressClass feature, StorageClass is going to be merged in a glimpse.

@bsctl may I ask you for some help?

**Comment by MaxFedotov** [comment]
@prometherion should we add additional webhooks for capsule, which will automatically assign `name` label on all of these resources? (on create\update cases, so this label cannot be deleted\modified by a user?)

**Comment by prometherion** [comment]
Gosh @MaxFedotov, I totally forgot this mention, replying lately!

> should we add additional webhooks for capsule, which will automatically assign name label on storage\ingress classes?

Honestly, I'm not a big fan of magic stuff runny under the hoods: __I create a resource and a new label is popping up and I cannot understand why this is happening__ can be raised by cluster administrators, as well generating continuous reconciliation in GitOps environments since the label would be applied by the GitOps engine since a label diff between current and desired resource would occur.

The `name` label is a limitation for Ingress and Storage class but for `capsule-proxy` 0.2.0 I would like to overcome it working on #57.

We have definitely to document these mandatory steps, otherwise listing and related actions wouldn't work as expected.

**Comment by prometherion** [comment]
@bsctl I just finished my assigned tasks for 0.1.0, I guess we're ready to draft the new documentation and, as well, the changelog!
