### ISSUE TITLE
A tenant owner can delete Storage/Ingress Classes

### ISSUE THREAD

**Issue by bsctl** [clastix/capsule-proxy#93]
## What's wrong
Giving storage/ingress classes access to the tenant owner, he can delete/modify them. That's could be an issue in case the storage/ingress class belongs to another tenant too.

## Hot to reproduce
1. As cluster admin, create a storage/ingress class and assign it to a tenant

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rook-retain
  labels:
    name: rook-retain
provisioner: rook
reclaimPolicy: Retain
```

2. As cluster admin, create a tenant and assign the storage class to it

```yaml
apiVersion: capsule.clastix.io/v1alpha1
kind: Tenant
metadata:
  name: oil
spec:
  owner:
    kind: User
    name: alice
  storageClasses:
    allowed:
    - rook-retain
    allowedRegex: ""
```

3. As tenant owner, Alice can get the storage class

```
$ kubectl get sc
NAME          PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-retain   rook          Retain          Immediate           false                  4h7m
```
Alice can delete the storage class

```
$ kubectl delete sc rook-retain
storageclass.storage.k8s.io "rook-retain" deleted
```

**Comment by MaxFedotov** [comment]
@prometherion i can fix it in the PR #91. 
Check request.Method, if isn't `GET` - fallback to `impersonateHandler` and return. WDYT?

**Comment by bsctl** [comment]
@prometherion @MaxFedotov this issue brings to review the current approach for this feature.

An alternative approach would be:

- in a shared scenario, where multiple tenants share nodes, storage/ingress classes, the tenant owner is not allowed to get/list/delete/patch any shared resource. It does make sense, imho.

- in the bring-your-own-device scenario, with dedicated nodes, storage/ingress classes, by default, tenant owners can get/list/delete/patch dedicated resource. It's responsibility of the cluster admin to assign dedicated resources to the tenants. In such case, there are no shared nodes, storage/ingress classes between tenants even if multiple tenants belong to the same owner, e.g. Alice.
 
This approach simplify the model without needing to add additional labels as 

```
capsule.clastix.io/enable-node-listing 
capsule.clastix.io/enable-node-update 
capsule.clastix.io/enable-node-deletion 
```
and make the usage more clear to the users.

Also we have to take care of RBAC:

```
$ kubectl auth can-i get sc/rook-retain
Warning: resource 'storageclasses' is not namespace scoped in group 'storage.k8s.io'
no - RBAC: clusterrole.rbac.authorization.k8s.io "capsule-tenant:argoproj.io" not found

$ kubectl get sc/rook-retain
NAME          PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
rook-retain   rook          Retain          Immediate           false                  15m

```

A bit confusing, isn't?

**Comment by prometherion** [comment]
Honestly, I would go for the additional labels, so `capsule.clastix.io/enable-{storageclass,ingressclass}-{listing.update,deletion}`: annotations are not cool, we all know, but it's good enough for the current status of Capsule itself.

Regarding RBAC, you're totally right: it's absolutely confusing, but I'd track this in another issue and plan the implementation for the next release cycle, _0.1.0 is coming_.

**Comment by prometherion** [comment]
> @prometherion i can fix it in the PR #91.
> Check request.Method, if isn't `GET` - fallback to `impersonateHandler` and return. WDYT?

Yes, just open a new PR pointing to this issue to keep track of all the implementations :)

**Comment by bsctl** [comment]
@prometherion we're specifying permissions, i.e. workaround RBAC with annotations. Is there any better way?

**Comment by bsctl** [comment]
@prometherion just an update on the RBAC. After a deep dive into the issue, noted we get the same behaviour by pointing the `kubectl` to APIs server without going through the `capsule-proxy` 

```
$ kubectl auth can-i get namespace/oil-development 
Warning: resource 'namespaces' is not namespace scoped
no

$ kubectl get namespace/oil-development 
NAME              STATUS   AGE
oil-development   Active   18h
```

The reason is that a `SelfSubjectAccessReview` is performed against the APIs server using the current namespace, e.g. that one set in the `kubeconfig` file:

```json
{
   "kind":"SelfSubjectAccessReview",
   "apiVersion":"authorization.k8s.io/v1",
   "metadata":{
      "creationTimestamp":null
   },
   "spec":{
      "resourceAttributes":{
         "namespace":"default",  // <-- note here
         "verb":"get",
         "resource":"namespaces",
         "name":"oil-development"
      }
   },
   "status":{
      "allowed":false
   }
}
```

In this case, we got a negative answer because no permissions in the `default` namespace for Alice

```json
{
   "kind":"SelfSubjectAccessReview",
   "apiVersion":"authorization.k8s.io/v1",
   "metadata":{
      "creationTimestamp":null,
      "managedFields":[]
   },
   "spec":{
      "resourceAttributes":{
         "namespace":"default",
         "verb":"get",
         "resource":"namespaces",
         "name":"oil-development"
      }
   },
   "status":{
      "allowed":false
   }
}

```

Changing the namespace

```
$ kubectl auth can-i get namespace/oil-development -n oil-development
Warning: resource 'namespaces' is not namespace scoped
yes

```

In this case, the `SelfSubjectAccessReview` is performed against the APIs server using the current namespace

```json
{
   "kind":"SelfSubjectAccessReview",
   "apiVersion":"authorization.k8s.io/v1",
   "metadata":{
      "creationTimestamp":null
   },
   "spec":{
      "resourceAttributes":{
         "namespace":"oil-development", // <-- note here
         "verb":"get",
         "resource":"namespaces",
         "name":"oil-development"
      }
   },
   "status":{
      "allowed":false
   }
}
```
Having this time a positive answer:

```json
{
   "kind":"SelfSubjectAccessReview",
   "apiVersion":"authorization.k8s.io/v1",
   "metadata":{
      "creationTimestamp":null,
      "managedFields":[]
   },
   "spec":{
      "resourceAttributes":{
         "namespace":"oil-development",
         "verb":"get",
         "resource":"namespaces",
         "name":"oil-development"
      }
   },
   "status":{
      "allowed":true,
      "reason":"RBAC: allowed by RoleBinding \"namespace:admin/oil-development\" of ClusterRole \"admin\" to User \"alice\""
   }
}
```

As conclusion, we do not have to fix this in `capsule-proxy`, just ask clarifications to the kubernetes community.

**Comment by MaxFedotov** [comment]
So, what do we do? The same thing with annotations as for nodes?

**Comment by bsctl** [comment]
@MaxFedotov as short term solution I would say yes according to @prometherion suggestion. In the long term, I prefer to implement RBAC similarly we made with namespaces. This will require the involvement of the **Capsule Operator** itself (creating/assigning RBAC roles) and use the `capsule-proxy` only for filtering.

For example:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: storage-class-viewer
rules:
- apiGroups: [""]
  resources: ["storageclass"]
  resourceNames: ["rook-retain", "rook-delete"]
  verbs: ["get", "list", "watch"]
```

By using regular RBAC instead of annotations, it should be more understandable by end users, imho.
