### ISSUE TITLE
Add support for k8s webhook token authentication strategy

### ISSUE THREAD

**Issue by gautam2187** [clastix/capsule-proxy#99]
Currently capsule-proxy assumes that the bearer token is a valid JWT token. This may not be the case with k8s clusters using webhook token authentication strategy as mentioned here https://kubernetes.io/docs/reference/access-authn-authz/authentication/#webhook-token-authentication

In this case bearer token could be a non JWT custom token that the webhook can process.

Currently webserver.go#checkJWTMiddleware passes the token to TokenReview and gets a populated TokenReview but the populated groups are not used down the chain. So, it fails the next check in webserver.go#checkUserInCapsuleGroupMiddleware.

**Comment by prometherion** [comment]
Thanks for reporting this @gautam2187, a nice enhancement since we weren't taking care of this strategy: going to add this to the 0.1.0 milestone!
